// Generated by copilot
type CenterProps = {
  children: React.ReactNode;
};
const Center: React.FC<CenterProps> = ({ children }) => {
  return <div className="m-4 flex justify-center">{children}</div>;
};
export default Center;
