// Generated by copilot

import { useEffect, useRef } from "react";

type ExampleObserverProps = {
  onIntersect: () => void;
  onLeave?: () => void;
};

const ExampleObserver = ({ onIntersect, onLeave }: ExampleObserverProps) => {
  const observerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      entries => {
        if (entries[0].isIntersecting) {
          onIntersect();
        } else if (onLeave) {
          onLeave();
        }
      },
      { threshold: 0.1 },
    );

    const currentRef = observerRef.current;
    if (currentRef) {
      observer.observe(currentRef);
    }

    return () => {
      if (currentRef) {
        observer.unobserve(currentRef);
      }
    };
  }, [onIntersect, onLeave]);

  return (
    <div ref={observerRef} className="card shadow-lg m-2">
      <div className="card-body">
        <h2 className="card-title">Observe me</h2>
      </div>
    </div>
  );
};

export default ExampleObserver;
