// Generated by copilot

import { useState } from "react";
import ExampleObserver from "./ExampleObserver";

const InfiniteScrollList: React.FC = () => {
  const [items, setItems] = useState<number[]>(
    Array.from({ length: 20 }, (_, i) => i),
  );

  const handleIntersect = () => {
    console.log("Element is in view!");
  };

  const handleLeave = () => {
    console.log("Element has left the view!");
  };

  const loadMoreItems = () => {
    setItems(prevItems => {
      const nextIndex = prevItems.length % 20;
      return [...prevItems, nextIndex];
    });
  };

  return (
    <div className="overflow-y-scroll h-96 w-96">
      {items.map((_item, index) => (
        <ExampleObserver
          key={index}
          onIntersect={
            index === items.length - 1 ? loadMoreItems : handleIntersect
          }
          onLeave={handleLeave}
        />
      ))}
    </div>
  );
};

export default InfiniteScrollList;
