// Generated by copilot

type UserInfoProps = {
  user: {
    id: number;
    name: string;
    email: string;
    phone: string;
    website: string;
  };
};

const UserInfo: React.FC<UserInfoProps> = ({ user }) => {
  return (
    <div className="card border shadow-lg m-2 w-1/3">
      <div className="card-body">
        <h2 className="card-title">User Info</h2>
        <h3>Name: {user.name}</h3>
        <p>User ID: {user.id}</p>
        <p>Email: {user.email}</p>
        <p>Phone: {user.phone}</p>
        <p>Website: {user.website}</p>
      </div>
    </div>
  );
};

export default UserInfo;
